CREATE DATABASE CUAHANGHOA
USE CUAHANGHOA




CREATE TABLE MATHANG(
	MaMH VARCHAR(10) PRIMARY KEY,
	TenMH NVARCHAR(255) NOT NULL,
	GiaMH NUMERIC(16,2),
	TonKho INT,
	MaDanhMuc VARCHAR(10) NOT NULL,
	MaNCC VARCHAR(10) NOT NULL,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE DANHMUC(
	MaDanhMuc VARCHAR(10) PRIMARY KEY,
	TenDanhMuc VARCHAR(255)

);
CREATE TABLE NHACUNGCAP(
	MaNCC VARCHAR(10) PRIMARY KEY,
	TenNCC VARCHAR(10) NOT NULL,
	SDT VARCHAR(20),
	Email VARCHAR(255)
);
CREATE TABLE GIAODICH(
	MaGiaoDich VARCHAR(10) PRIMARY KEY,
	LoaiGiaoDich VARCHAR(20) NOT NULL,
	DoitacGiaoDich VARCHAR(20) NOT NULL CHECK (DoiTacGiaoDich IN ('NHACUNGCAP','KHACHHANG')),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE PHIEUTHU (
	MaPhieuthu VARCHAR(10) PRIMARY KEY,
	MaGiaoDich VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10) NOT NULL, 
	MaHoaDonBan VARCHAR(10),
	MoTa VARCHAR(255),
	TongTien NUMERIC(16,2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE PHIEUCHI (
	MaPhieuChi VARCHAR(10) PRIMARY KEY,
	MaGiaoDich VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10) NOT NULL, 
	MaHoaDonMua VARCHAR(10) NOT NULL,
	MoTa VARCHAR(255),
	TongTien NUMERIC(16,2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE CHUNGTUNHAPKHO (
	MaChungTuNhap VARCHAR(10) PRIMARY KEY ,
	MaHopDongMua VARCHAR(10) NOT NULL,
	MaNCC VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10),
	DiaDiem VARCHAR(255),
	TongGiaTri NUMERIC(16,2),
	ThongTinLoHang TEXT,
	GhiChu TEXT,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE SONHAPKHO (
	MaNhap VARCHAR(10) PRIMARY KEY,
	MaChungTuNhap VARCHAR(10) NOT NULL,
	MaMH VARCHAR(10) NOT NULL,
	SoLuong INT,
	Thanhtien NUMERIC(16,2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE CHUNGTUXUATKHO (
	MaChungTuXuat VARCHAR(10) PRIMARY KEY ,
	MaNV VARCHAR(10),
	DiaDiem VARCHAR(255),
	TongGiaTri NUMERIC(16,2),
	ThongTinLoHang TEXT,
	GhiChu TEXT,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE SOXUATKHO (
	MaXuat VARCHAR(10) PRIMARY KEY,
	MaChungTuXuat VARCHAR(10) NOT NULL,
	MaMH VARCHAR(10) NOT NULL,
	SoLuong INT,
	Thanhtien NUMERIC(16,2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);


-- Bảng Báo giá
CREATE TABLE BAOGIA (
    MaBaoGia VARCHAR(10) PRIMARY KEY,
    SoBaoGia VARCHAR(50),
    MaNCC VARCHAR(10) ,
    ThongTinKhac VARCHAR(100),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
	
-- Bảng Chi tiết báo giá
CREATE TABLE CHITIETBAOGIA (
    MaCTBaoGia VARCHAR(10) PRIMARY KEY,
    MaBaoGia VARCHAR(10),
    MaMH VARCHAR(10),
    SoLuong INT,
    DonGia NUMERIC(10, 2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
   
);

-- Bảng Hợp đồng
CREATE TABLE HOPDONGMUAHANG (
    MaHopDongMua VARCHAR(10) PRIMARY KEY,
	MaBaoGia VARCHAR(10),
    SoHopDong VARCHAR(50),
    MaNCC VARCHAR(10),
	ChietKhau FLOAT,
	GTGT FLOAT,
	TongGiaTri NUMERIC(16,2),
    NgayGiaoDukien DATETIME,
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);

-- Bảng Chi tiết hợp đồng
CREATE TABLE CTHOPDONGMUAHANG (
    MaCTHopDongMua VARCHAR(10) PRIMARY KEY,
    MaHopDongMua VARCHAR(10),
    MaMH VARCHAR(10),
    SoLuong INT,
    DonGia NUMERIC(10, 2),
	Thanhtien NUMERIC(10,2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);

CREATE TABLE HOADONMUAHANG (
	MaHoaDonMua VARCHAR(10) PRIMARY KEY,
	MaHopDongMua VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10) NOT NULL,
	MaNCC VARCHAR(10) NOT NULL,
	TongGiaTri NUMERIC(16,2) ,
	PhuongThucThanhToan VARCHAR(30),
	TrangThai VARCHAR(30),
	GhiChu TEXT, 
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE DONHANG(
	MaDH VARCHAR(10) PRIMARY KEY,
	MaKH VARCHAR(10) NOT NULL,
	TongGiaTri NUMERIC(16,2),
	GiamGia FLOAT,
	ThanhTien NUMERIC(16,2),
	TrangThai VARCHAR(20),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE CHITIETDONHANG(
	MaCTDon VARCHAR(10) PRIMARY KEY,
	MaDH VARCHAR(10),
	MaMH VARCHAR(10),
	SoLuong INT,
	Dongia NUMERIC(16,2),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE HOADONBANHANG(
	MaHoaDonBan VARCHAR(10) PRIMARY KEY,
	MaDH VARCHAR(10) NOT NULL,
	MaKH VARCHAR(10) NOT NULL,
	MaNV VARCHAR(10) NOT NULL,
	TongGiaTri NUMERIC(16,2),
	PhuongThucThanhToan VARCHAR(30),
	TrangThai VARCHAR(30),
	GhiChu TEXT, 
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE KHACHHANG(
	MaKH VARCHAR(10) PRIMARY KEY,
	TenKH VARCHAR(255),
	GioiTinh VARCHAR(3),
	NgaySinh DATE,
	DiaChi VARCHAR(255),
	SDT VARCHAR(20),
	Email VARCHAR(20),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE NHANVIEN (
	MaNV VARCHAR(10) PRIMARY KEY,
	MaTP VARCHAR(10),
	MaBoPhan VARCHAR(10),
	TenNV VARCHAR(255),
	GioiTinh VARCHAR(3),
	NgaySinh DATE,
	DiaChi VARCHAR(255),
	SDT VARCHAR(20),
	Email VARCHAR(20),
	TGTao DATETIME DEFAULT GETDATE(),
	TGCapNhat DATETIME DEFAULT GETDATE()
);
CREATE TABLE BOPHAN(
	MaBoPhan VARCHAR(10) PRIMARY KEY ,
	TenBoPhan VARCHAR(10)
);

--SO NHAP KHO
ALTER TABLE SONHAPKHO
ADD CONSTRAINT FK_SONHAPKHO_CHUNGTUNHAPKHO
FOREIGN KEY (MaChungTuNhap) REFERENCES CHUNGTUNHAPKHO(MaChungTuNhap);
ALTER TABLE SONHAPKHO
ADD CONSTRAINT FK_SONHAPKHO_MATHANG
FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH);
-- SO XUAT KHO

ALTER TABLE SOXUATKHO
ADD CONSTRAINT FK_SOXUATKHO_MATHANG
FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH);
ALTER TABLE SOXUATKHO
ADD CONSTRAINT FK_SOXUATKHO_CHUNGTUXUATKHO
FOREIGN KEY (MaChungTuXuat) REFERENCES CHUNGTUXUATKHO(MaChungTuXuat);
--HOP DONG MUA HANG
ALTER TABLE HOPDONGMUAHANG
ADD CONSTRAINT FK_HOPDONGMUAHANG_BAOGIA
FOREIGN KEY (MaBaoGia) REFERENCES BAOGIA(MaBaoGia);

ALTER TABLE HOPDONGMUAHANG
ADD CONSTRAINT FK_HOPDONGMUAHANG_NHACUNGCAP
FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);

-- Bảng PHIEUTHU
ALTER TABLE PHIEUTHU
ADD CONSTRAINT FK_PHIEUTHU_GIAODICH
FOREIGN KEY (MaGiaoDich) REFERENCES GIAODICH(MaGiaoDich);

ALTER TABLE PHIEUTHU
ADD CONSTRAINT FK_PHIEUTHU_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE PHIEUTHU
ADD CONSTRAINT FK_PHIEUTHU_HOADONBANHANG
FOREIGN KEY (MaHoaDonBan) REFERENCES HOADONBANHANG(MaHoaDonBan);
-- Bảng PHIEUCHI
ALTER TABLE PHIEUCHI
ADD CONSTRAINT FK_PHIEUCHI_GIAODICH
FOREIGN KEY (MaGiaoDich) REFERENCES GIAODICH(MaGiaoDich);

ALTER TABLE PHIEUCHI
ADD CONSTRAINT FK_PHIEUCHI_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE PHIEUCHI
ADD CONSTRAINT FK_PHIEUCHI_HOADONMUAHANG
FOREIGN KEY (MaHoaDonMua) REFERENCES HOADONMUAHANG(MaHoaDonMua);
-- Bảng CHUNGTUNHAPKHO


ALTER TABLE CHUNGTUNHAPKHO
ADD CONSTRAINT FK_CHUNGTUNHAPKHO_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CHUNGTUNHAPKHO
ADD CONSTRAINT FK_CHUNGTUNHAPKHO_NHACUNGCAP
FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);

ALTER TABLE CHUNGTUNHAPKHO
ADD CONSTRAINT FK_CHUNGTUNHAPKHO_HOPDONGMUAHANG 
FOREIGN KEY (MaHopDongMua) REFERENCES HOPDONGMUAHANG(MaHopDongMua);
-- Bảng CHUNGTUXUATKHO



ALTER TABLE CHUNGTUXUATKHO
ADD CONSTRAINT FK_CHUNGTUXUATKHO_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
-- Bảng BOPHAN
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_BOPHAN
FOREIGN KEY (MaBoPhan) REFERENCES BOPHAN(MaBoPhan);

-- Bảng CHITIETBAOGIA
ALTER TABLE CHITIETBAOGIA
ADD CONSTRAINT FK_CHITIETBAOGIA_BAOGIA
FOREIGN KEY (MaBaoGia) REFERENCES BAOGIA(MaBaoGia);

ALTER TABLE CHITIETBAOGIA
ADD CONSTRAINT FK_CHITIETBAOGIA_MATHANG
FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH);


-- Bảng MATHANG
ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_DANHMUC
FOREIGN KEY (MaDanhMuc) REFERENCES DANHMUC(MaDanhMuc);
 
ALTER TABLE MATHANG
ADD CONSTRAINT FK_MATHANG_NHACUNGCAP
FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
-- Bảng BAOGIA 
ALTER TABLE BAOGIA
ADD CONSTRAINT FK_BAOGIA_NHACUNGCAP
FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
--Bảng CHITIETHOPDONGMUA
ALTER TABLE CTHOPDONGMUAHANG
ADD CONSTRAINT FK_CTHOPDONGMUAHANG_HOPDONGMUAHANG
FOREIGN KEY (MaHopDongMua) REFERENCES HOPDONGMUAHANG(MaHopDongMua);

ALTER TABLE CTHOPDONGMUAHANG
ADD CONSTRAINT FK_CTHOPDONGMUAHANG_MATHANG
FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH);
-- Bảng HOADONMUAHANG
ALTER TABLE HOADONMUAHANG
ADD CONSTRAINT FK_HOADONMUAHANG_HOPDONGMUAHANG
FOREIGN KEY (MaHopDongMua) REFERENCES HOPDONGMUAHANG(MaHopDongMua);

ALTER TABLE HOADONMUAHANG
ADD CONSTRAINT FK_HOADONMUAHANG_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE HOADONMUAHANG
ADD CONSTRAINT FK_HOADONMUAHANG_NHACUNGCAP
FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
-- Bảng DONHANG 
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);
-- Bảng CHITIETDONHANG 
ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_DONHANG
FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH);

ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_MATHANG
FOREIGN KEY (MaMH) REFERENCES MATHANG(MaMH);
-- Bảng HOADONBANHANG 
ALTER TABLE HOADONBANHANG
ADD CONSTRAINT FK_HOADONBANHANG_DONHANG
FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH);

ALTER TABLE HOADONBANHANG
ADD CONSTRAINT FK_HOADONBANHANG_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE HOADONBANHANG
ADD CONSTRAINT FK_HOADONBANHANG_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
